#log_filter = "where_am_i::nmea::codec=trace,info"
#log_filter = "info"
log_filter = "trace"

[[gps]]
name = "GPS0"
device = "/dev/tty.BT-GPS-396654-BT-GPSCOM"
gps_type = "mkt"
baud_rate = 38400
ntp_unit = 2
messages = [ "RMC" ]
