[package]
name = "where_am_i"
version = "0.1.0"
authors = ["Eric Hodel <drbrain@segment7.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nmea   = "0.0.8"
tokio = { version = "0.2", features = ["full"] }

[patch.crates-io]
nmea = { git = "https://github.com/AeroRust/nmea" }
