[package]
name = "where_am_i"
version = "0.1.0"
authors = ["Eric Hodel <drbrain@segment7.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh               = "0.1.0"
chrono             = "0.4.0"
json               = "0.12"
libc               = "0.2.0"
nix                = "0.17.0"
nmea               = "0.0.8"
tokio              = { version = "0.2", features = ["full"] }
tokio-serial       = "4.3.0"
tracing            = "0.1.0"
tracing-futures    = "0.2.0"
tracing-subscriber = "0.2.0"

[patch.crates-io]
nmea = { path = "../nmea" }
#nmea = { git = "https://github.com/AeroRust/nmea" }
#tokio = { path = "../tokio/tokio" }

