[package]
name = "afl"
version = "0.0.0"
authors = ["Eric Hodel <drbrain@segment7.net>"]
edition = "2018"
publish = false

[[bin]]
name = "nmea_message"
path= "src/bin/nmea_message.rs"

[dependencies]
afl = "*"
nom = "5.1.0"

[dependencies.where_am_i]
path = ".."

